ExaminationSystem/Models/Question.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.Extensions.Hosting;

namespace ExaminationSystem.Models
{
	public class Question
	{
		public int Id { get; set; }
		[ValidateNever]
		public string QuestionTitle { get; set; }
		public int Score { get; set; } = 5;
		[ValidateNever]
		public List<Exam> Exams { get; } = [];
		[ValidateNever]
		public List<Answer> Answers { get; } = [];
	}
}

ExaminationSystem/Controllers/AnswerController.cs
using DataAccessLayer.DTOs;
using DataAccessLayer.Models;
using DataAccessLayer.Interfaces;
using Microsoft.AspNetCore.Mvc;
using BusinessLogicLayer;

namespace ExaminationSystem.Controllers
{
	public class AnswerController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
		private readonly ApplicationDbContext _context;

		public AnswerController(IUnitOfWork unitOfWork, ApplicationDbContext context)
		{
			_unitOfWork = unitOfWork;
			_context = context;
		}
		public async Task<IActionResult> Index(int id)
		{
			var models = await _unitOfWork.answers.GetAll(x => x.QuestionId == id, "Question");
			if (models == null)
			{
				return NotFound();
			}
			var dto = new AnswerQuestionDto
			{
				answersQuestion = models,
				questionId = id

			};
			return View(dto);
		}
		[HttpGet]
		public async Task<IActionResult> Create(int id)
		{
			var answers = await _unitOfWork.answers.GetAll(x => x.QuestionId == id);

			var dto = new AnswerDto
			{
				answers = answers,
				questionId = id,
			};

			return View(dto);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(AnswerDto dto)
		{
			try
			{
				if (ModelState.IsValid)
				{
					var answers = await _unitOfWork.answers.GetAll(x => x.QuestionId == dto.questionId);
					var answerModel = new Answer
					{
						AnswerDescription = dto.answer,
						isTrue = dto.isTrue,
						QuestionId = dto.questionId
					};
					await _unitOfWork.answers.Create(answerModel);
					await _unitOfWork.complete();
					return RedirectToAction("Index", new { id = dto.questionId });
				}
				return View(dto);
			}
			catch
			{
				return View();
			}
		}
		public async Task<IActionResult> Edit(int id)
		{
			var model = await _unitOfWork.answers.GetById(x => x.Id == id);
			if (model == null)
			{
				return NotFound();
			}
			return View(model);
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(Answer model)
		{
			try
			{
				if (ModelState.IsValid)
				{
					await _unitOfWork.answers.Update(model);
					await _unitOfWork.complete();
					return RedirectToAction(nameof(Index), new { id = model.QuestionId });
				}

				return View(model);
			}
			catch
			{
				return View();
			}
		}

		[HttpGet]
		public async Task<IActionResult> Delete(int id)
		{
			var model = await _unitOfWork.answers.GetById(x => x.Id == id, "Question");
			if (model == null)
			{
				return NotFound();
			}
			return View(model);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Delete(Answer model)
		{
			try
			{
				if (ModelState.IsValid)
				{
					var questionId = model.QuestionId;
					await _unitOfWork.answers.Delete(model);
					await _unitOfWork.complete();
					return RedirectToAction(nameof(Index), new { id = questionId });
				}

				return View(model);
			}
			catch
			{
				return View();
			}
		}
	}
}

ExaminationSystem/Controllers/QuestionController.cs
using DataAccessLayer.Interfaces;
using DataAccessLayer.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ExaminationSystem.Controllers
{

	public class QuestionController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
		public QuestionController(IUnitOfWork unitOfWork)
		{
			_unitOfWork = unitOfWork;
		}
		public async Task<IActionResult> Index()
		{
			var models = await _unitOfWork.questions.GetAll();
			return View(models);
		}
		public ActionResult Create()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(Question model)
		{
			try
			{
				if (ModelState.IsValid)
				{
					await _unitOfWork.questions.Create(model);
					await _unitOfWork.complete();
					return RedirectToAction(nameof(Index));
				}
				return View(model);
			}
			catch
			{
				return View();
			}
		}

		public async Task<IActionResult> Edit(int id)
		{
			var model = await _unitOfWork.questions.GetById(x => x.Id == id);
			if (model == null)
			{
				return NotFound();
			}
			return View(model);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(Question model)
		{
			try
			{
				if (ModelState.IsValid)
				{
					await _unitOfWork.questions.Update(model);
					await _unitOfWork.complete();
					return RedirectToAction(nameof(Index));
				}

				return View(model);
			}
			catch
			{
				return View();
			}
		}

		public async Task<IActionResult> Delete(int id)
		{
			var model = await _unitOfWork.questions.GetById(x => x.Id == id);
			if (model == null)
			{
				return NotFound();
			}
			return View(model);
		}

		// POST: QuestionController/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Delete(Question model)
		{
			try
			{
				if (ModelState.IsValid)
				{
					var answer = await _unitOfWork.answers.GetAll(x => x.QuestionId == model.Id);
					await _unitOfWork.questions.Delete(model);
					await _unitOfWork.complete();
					if (answer != null)
					{
						foreach (var item in answer)
						{
							await _unitOfWork.answers.Delete(item);
							await _unitOfWork.complete();
						}
					}

					return RedirectToAction(nameof(Index));
				}

				return View(model);
			}
			catch
			{
				return View();
			}
		}
	}
}

ExaminationSystem/Views/Question/Create.cshtml
@model Question

@{
    ViewData["Title"] = "Create";
}

<h1>Create New Question</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="QuestionTitle" class="control-label"></label>
                <input asp-for="QuestionTitle" class="form-control" />
                <span asp-validation-for="QuestionTitle" class="text-danger"></span>
            </div>
            <div class="form-group text-lg-start mt-4 pt-2">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a class="btn btn-danger" asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ExaminationSystem/Views/Question/Delete.cshtml
@model Question

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete Question</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QuestionTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QuestionTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Score)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Score)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a class="btn btn-success" asp-action="Index">Back to List</a>
    </form>
</div>

ExaminationSystem/Views/Question/Edit.cshtml
@model Question

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Question</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="QuestionTitle" class="control-label"></label>
                <input asp-for="QuestionTitle" class="form-control" />
                <span asp-validation-for="QuestionTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Score" class="control-label"></label>
                <input asp-for="Score" class="form-control" />
                <span asp-validation-for="Score" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a class="btn btn-danger" asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ExaminationSystem/Views/Question/Index.cshtml
@model IEnumerable<Question>

@{
	ViewData["Title"] = "Index";
}

<h1>List of Questions</h1>

<p>
	<a class="btn btn-primary" asp-action="Create">Create New Question</a>
</p>
<table class="table table-striped table-bordered ">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.QuestionTitle)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Score)
			</th>
			<th style="width:22%">Actions</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.QuestionTitle)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Score)
				</td>
				<td>
					<a class="btn btn-primary" asp-controller="Answer" asp-action="Index" asp-route-id="@item.Id">View answers</a> |
					<a class="btn btn-success" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
					<a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">X</a>
				</td>
			</tr>
		}
	</tbody>
</table>